In [46]:
import numpy as np

In [ ]:
# page 1

In [39]:
page1_geolocations = ['Blueberry Hill',
 'Will Rogers State Historic Park',
 'Oatman',
 'Meteor Crater',
 'Chicago',
 'Lincoln',
 'Big Piney River',
 'America',
 'Tacoma',
 'Palo Duro Canyon State Park',
 'Amarillo',
 'Los Angeles',
 'Santa Monica',
 'Kingman',
 'Lebanon',
 'El Morro National Monument',
 'Acoma',
 'Palisades Park',
 'St. Louis',
 'Stroud',
 'San Bernardino',
 'Rialto',
 'Pacific',
 'Needles',
 'Springfield',
 'Seligman',
 'Colorado River',
 'Route 66',
 'Palo Duro Canyon',
 'Loop',
 'Tucumcari',
 'Chain of Rocks Bridge',
 'Route 66 Museum',
 'Hackberry General Store',
 'Ozarks',
 'Shirley',
 'Oklahoma City',
 'Clinton',
 'Grants',
 'Funks Grove',
 "Devil's Elbow",
 'Tulsa',
 'Jack Smith Park',
 'Woody Guthrie Center',
 'Cozy Dog Drive In',
 'Delmar Loop',
 'Lone Star State',
 'Cadillac Ranch',
 'Oklahoma Route 66 Museum',
 'Munger Moss Motel',
 'Blue Swallow Motel',
 'Wigwam Motel',
 'Rock Cafe',
 'Oatman Hotel',
 'Meramec Caverns',
 'El Garces',
 'Amtrak',
 "Cain's Ballroom"]

In [23]:
page1 = {
    "Route 66": 1, 
    "Chicago": 1,
    "Santa Monica": 1,
    "America": 2,   # incorrectly geocoded
    "Tulsa": 1,
    "Cozy Dogs": 3, # no gazetteer entry
    "Springfield": 1,
    "Illinois": 1,
    "Cozy Dog Drive In": 1,
    "Funks Grove Pure Maple Sirup": 4, # spacy failed to extract
    "Shirley": 1,
    "Illinois Funks": 3, # no gazetteer entry
    "Chain of Rocks Bridge": 1, 
    "Mississippi": 2,
    "Missouri": 1,
    "St. Louis": 1, 
    "Delmar Loop": 1,
    "Blueberry Hill":1,
    "Meramec Caverns": 1,
    "Missouri": 1,
    "Munger Moss Motel": 1, 
    "Lebanon": 1, 
    "Elbow Inn Bar": 3,
    "Big Piney River": 1,
    "Ozarks": 1,
    "Tulsa": 1,
    "Cain's Ballroom": 1,
    "Woody Guthrie Center": 1,
    "Rock Cafe": 1,
    "Stroud": 1,
    "Oklahoma": 1,
    "Oklahoma City": 1,
    "Route 66 Museum": 1,
    "Clinton": 1,
    "Jiggs Smokehouse": 3,
    "Palo Duro Canyon State Park": 1,
    "Texas": 1,
    "Amarillo": 1,
    "Cadillac Ranch": 1, 
    "Palo Duro Canyon": 1, 
    "Tucumcari": 1, 
    "New Mexico": 1,
    "Blue Swallow Motel": 1,
    "Odeon Theatre": 3,
    "El Morro National Monument": 1,
    "Acoma": 1,
    "Meteor Crater": 1,
    "Arizona": 1, 
    "Kingman": 1,
    "Hackberry General Store": 1,
    "Oatman": 1,
    "Oatman Hotel": 1,
    "Needles": 2,        # 
    "California": 1,
    "Colorado River": 0, # rule based failed
    "Jack Smith Park": 1,
    "El Garces": 1,
    "Wigwam Motel": 23, # no gazetteer entry in the region mentioned
    "Rialto": 1,
    "San Bernardino": 1,
    "Will Rogers State Historic Park": 1,
    "Los Angeles": 1,
    "Santa Monica": 1,
    "Palisades Park": 7    
}

In [56]:
np.unique(np.array(list(page1.values())), return_counts=True)

(array([ 0,  1,  2,  3,  4,  7, 23]), array([ 1, 49,  3,  5,  1,  1,  1]))

In [24]:
sum([1 for i in page1.values() if i == 1]) / len(page1.values())

0.8032786885245902

In [40]:
page2_geolocations = ['Santa Ynez',
 'Santa Barbara',
 'Southern California',
 'Orange County',
 'Long Beach',
 'Crystal Cove State Park',
 'Pismo',
 'Los Trancos Creek',
 'Huntington Beach',
 'Newport Beach',
 'Pismo Beach',
 'Long Beach Convention and Entertainment Center',
 'Pacific',
 'Harbor House Inn',
 'Ripley',
 'Avila Beach',
 'Mendenhall',
 'El Paseo',
 'Arroyo Grande',
 'Hearst Castle',
 'Trout Creek Trail',
 'Lompoc',
 'State Street',
 'Buellton',
 'Aquarium of the Pacific',
 'Vandenberg Air Force Base',
 'Pea Soup Andersen',
 'Edna Valley',
 'Dunes Center',
 'Huntington Pier',
 'La Purisima Mission',
 'Guadalupe-Nipomo Dunes',
 'SoCal',
 'International Surfing Museum']

In [34]:
page2 = {
    "Southern California": 1, 
    "Pismo Beach": 1,
    "Pismo": 1,
    "Guadalupe-Nipomo Dunes": 1,
    "Dunes Center": 1,
    "Guadalupe": 3,
    "Avila Beach": 1,
    "Trout Creek Trail": 1, # google doesn't know this place, :=))
    "Arroyo Grande": 1,
    "Edna Valley": 1, # google doens't know this place
    "Vandenberg Air Force Base": 1, 
    "Lompoc": 1, 
    "La Purisima Mission": 1,
    "California": 1, 
    "Buellton": 1,
    "Pea Soup Andersen": 1,
    "Hearst Castle": 1,
    "Mendenhall’s Museum of Gas Pumps and Petroliana": 4, # spacy
    "OstrichLand USA": 3,
    "Santa Ynez": 1,
    "Santa Barbara": 1,
    "State Street": 1,
    "El Paseo": 1,
    "Harbor House Inn": 1, 
    "Huntington Beach": 1,
    "Huntington Pier": 1,
    "International Surfing Museum": 1,
    "Aquarium of the Pacific": 1,
    "Long Beach": 1,
    "Long Beach Convention and Entertainment Center": 1,
    "Crystal Cove State Park": 1,
    "Orange County": 1,
    "Crystal Cove Beach Cottages": 3,
    "Los Trancos Creek": 1
}

In [55]:
np.unique(np.array(list(page2.values())), return_counts=True)

(array([1, 3, 4]), array([30,  3,  1]))

In [35]:
sum([1 for i in page2.values() if i == 1]) / len(page2.values())

0.8823529411764706

In [41]:
page3_geolocations = Tunnel LogTunnel LogTunnel LogTunnel LogTunnel Log['Crescent Rock',
 'Piedmont',
 'Baymont Inn & Suites',
 'Big Meadows Lodge',
 'Charlies Bunion',
 'Clingmans Dome',
 'Gateway Airport',
 'Great Smoky Mountains National Park',
 'Mammoth Cave',
 'Gatlinburg',
 'Calvary Rocks',
 'Hawksbill Mountain',
 'LeConte Lodge',
 'Green River',
 'Smoky Mountains',
 'Rapidan Camp',
 'George Washington Memorial Parkway',
 'Cave City',
 'Skyline Drive',
 'Shenandoah Valley',
 'Shenandoah River',
 'Great Smoky Mountains',
 'Cades Cove',
 'Mount Le Conte',
 'Blue Ridge Parkway',
 'Grotto Falls',
 'Chimney Tops',
 'Skyland',
 'Deep Creek Trail',
 'Catoosa Wildlife Management Area',
 'Union',
 'Compton Peak',
 'Arlington',
 'Shenandoah National Park',
 'Skyland Resort',
 'Ronald Reagan Washington National Airport',
 'Cataloochee',
 'Shenandoah',
 'Mammoth Cave National Park',
 'Newfound Gap',
 'Manassas National Battlefield Park',
 'Cedar Sink',
 'Buckhorn Inn',
 'Trillium Gap Trail',
 'Frozen Niagara',
 'I-64W',
 'Pollock Dining Room',
 'Indian Creek Falls',
 'Blackrock Summit',
 'Tuscarora-Overall Run Trail',
 'Cataloochee Valley',
 'Cades Cove Campground Store',
 'Mammoth Cave Hotel',
 'Crystal Lake Café',
 'Appalachian Trail']

In [37]:
page3 = {
    "Ronald Reagan Washington National Airport": 1,
    "Arlington": 1,
    "Virginia": 1,
    "Shenandoah": 2,
    "Great Smoky Mountains": 1,
    "Mammoth Cave": 1,
    "Shenandoah National Park": 1,
    "Skyline Drive": 1,
    "Shenandoah National Park": 1,
    "Piedmont": 1,
    "Shenandoah Valley": 1,
    "George Washington Memorial Parkway": 1,
    "Manassas National Battlefield Park": 1,
    "Skyland Resort": 1,
    "Shenandoah River": 1,
    "Shenandoah Valley": 1,
    "Pollock Dining Room": 1,
    "Big Meadows Lodge": 1,
    "Spottswood Dining Room": 3,
    "Crescent Rock": 1,
    "Hawksbill Mountain": 2,
    "Rapidan Camp": 1,
    "Blackrock Summit": 1,
    "Compton Peak": 1,
    "Overall Run Falls": 3,
    "Calvary Rocks": 1,
    "Great Smoky Mountains National Park": 1,
    "Smoky Mountains": 1,
    "Blue Ridge Parkway": 1,
    "LeConte Lodge": 1,
    "Buckhorn Inn": 3,
    "Baymont Inn & Suites": 3,
    "Cades Cove Campground Store": 1,
    "Cades Cove": 1,
    "Clingmans Dome": 1,
    "Grotto Falls": 1,
    "Deep Creek Trail": 1,
    "Newfound Gap": 1,
    "Charlies Bunion": 1,
    "Chimney Tops": 1,
    "Mount Le Conte": 1,
    "Cataloochee Valley": 1,
    "Mammoth Cave National Park": 1,
    "Catoosa Wildlife Management Area": 1,
    "Mammoth Cave Hotel": 1,
    "Crystal Lake Café": 3,
    "Watermill Restaurant": 3,
    "Green River": 1,
    "Cedar Sink": 1,
    "Frozen Niagara": 1
}

In [54]:
np.unique(np.array(list(page3.values())), return_counts=True)

(array([1, 2, 3]), array([40,  2,  6]))

In [42]:
sum([1 for i in page3.values() if i == 1]) / len(page3.values())

0.8333333333333334

In [43]:
page4_geolocations = ['Kings Canyon Scenic Byway',
 'Wawona',
 'Yosemite',
 'Furnace Creek',
 'Kings River',
 'Scotty’s Castle',
 'Glacier Point',
 'Vernal',
 'Kings Canyon National Park',
 'Sequoia Park',
 'Sierra',
 'Taft Point',
 'Stovepipe Wells',
 'General Grant Tree',
 'Yosemite National Park',
 'Furnace Creek Ranch',
 'Grizzly Giant',
 'Death Valley National Park',
 'Badwater',
 'Death Valley',
 'Lower Yosemite Fall',
 'Badger Pass',
 'Las Vegas',
 'Ubehebe Crater',
 'Dante’s View',
 'Half Dome',
 'Hume Lake',
 'Manzanar National Historic Site',
 'Alabama Hills',
 'Mariposa Grove',
 'Lodgepole',
 'Olmsted Point',
 'Wildrose Peak',
 'Vernal Fall',
 'Furnace Creek Inn',
 'Mirror Lake',
 'Ash Mountain',
 'Sentinel Dome',
 'General Sherman Tree',
 'Merced River',
 'Yosemite Valley',
 'El Capitan',
 'Coarsegold',
 'Crystal Cave',
 'Lone Pine',
 'Mist Trail',
 'Sequoia',
 'Zabriskie Point',
 'Yosemite Falls',
 'Tunnel Log',
 'Death Valley Junction',
 'Mono Lake',
 'Mount Whitney',
 'Nevada Falls',
 'Moro Rock',
 'Sierra Nevada',
 'Kings Canyon',
 'Swinging Bridge',
 'Giant Forest',
 'Golden Canyon',
 'Glacier Point Road',
 'Artists Drive',
 'The Ahwahnee Hotel',
 'Wildrose Charcoal Kilns',
 'Grants Grove',
 'Underground Tour',
 'Wuksachi Lodge',
 'McCarran International',
 'Furnace Creek Resort',
 'Tioga Pass Road',
 'Peaks Restaurant',
 'North Grove Loop',
 'Crescent Meadow Road']

In [44]:
page4 = {
    "McCarran International": 1,
    "Las Vegas": 1,
    "Nevada": 1,
    "California": 1,
    "Sierra Nevada": 1,
    "Death Valley": 7,
    "Mount Whitney": 1,
    "Sequoia": 2,
    "Yosemite Falls": 1,
    "Yosemite": 1,
    "Death Valley National Park": 1,
    "Death Valley Junction": 1,
    "Amargosa Opera House and Hotel": 3,
    "Furnace Creek Resort": 1,
    "Furnace Creek Inn": 1,
    "Badwater": 1,
    "Scotty’s Castle": 1,
    "Stovepipe Wells": 1, 
    "Zabriskie Point": 1,
    "Furnace Creek": 1,
    "Golden Canyon": 2, # several results in one region, 
    "Red Cathedral": 3, # hiking area
    "Wildrose Charcoal Kilns": 1,
    "Wildrose Peak": 1,
    "Ubehebe Crater": 1,
    "Yosemite National Park": 1,
    "Merced River": 1,
    "Alabama Hills": 1,
    "Lone Pine": 1,
    "Manzanar National Historic Site": 1,
    "Mono Lake": 1,
    "Ahwahnee Hotel": 4,
    "Lower Yosemite Fall": 1,
    "Yosemite Valley": 1,
    "Half Dome": 1,
    "Olmsted Point": 1,
    "Mirror Lake": 3,
    "Mariposa Grove": 1,
    "Wawona": 1,
    "Grizzly Giant": 1,
    "Glacier Point": 1,
    "Taft Point": 1,
    "Sentinel Dome": 1,
    "General Sherman Tree": 1,
    "Coarsegold": 1,
    "Wuksachi Lodge": 1,
    "Wolverton Meadow": 2, # used different name than in gazetteer, str similarity failed
    "Giant Forest": 1,
    "Crystal Cave": 1,
    "Congress Trail": 4,
    "Kings Canyon": 1,
    "North Grove Loop": 3,
    "General Grant Tree": 1,
    "Kings Canyon Scenic Byway": 1, 
    "Hume Lake": 1,
    "Kings River": 1,
    "Moro Rock": 1,
    "Ash Mountain": 3,
    "Tunnel Log": 1,
    "Crescent Meadow Road": 1
}

In [53]:
np.unique(np.array(list(page4.values())), return_counts=True)

(array([1, 2, 3, 4, 7]), array([49,  3,  5,  2,  1]))

In [45]:
sum([1 for i in page4.values() if i == 1]) / len(page4.values())

0.8166666666666667

In [57]:
page5_geolocations = ['Westcliffe',
 'Zapata Ranch',
 'Paonia',
 'Valley View Hot Springs',
 'Grand Junction',
 'La Veta',
 'Zapata Falls',
 'Florence',
 'North Fork Valley',
 'Black Canyon',
 'Baca National Wildlife Refuge',
 'Gunnison River',
 'South Rim',
 'Lizard',
 'Ragged Mountains',
 'Colorado Springs',
 'Moab',
 'Milky Way',
 'Spanish Peaks',
 'Paonia Reservoir',
 'San Luis Valley',
 'Wild West',
 'Great Sand Dunes National Park',
 'Crestone',
 'Colorado National Monument',
 'Midwest',
 'Bluff Park',
 'Willow Lake',
 'Silver Cliff',
 'Saddlehorn Campground',
 'Book Cliffs View',
 'South Rim Campground',
 'Piñon Flats',
 'Great Sand Dunes',
 'The Crestone Peaks',
 'Paint Mines Interpretive Park',
 'Ziggurat',
 'Ryus Avenue Bakery',
 'Southwest Colorado',
 'Colorado FIVE',
 'Paonia State Park',
 'Black Canyon of',
 'Bross Hotel',
 'Smokey Jack Observatory',
 'American Viticulture Area',
 'Gunnison National Park']

* 1 # extracted and correctly geocoded
* 2 # incorrectly geocoded
* 3 # no gazetteer entry
* 4 # spacy failed to extract
* 5 # not relevant point filtered out
* 6 # dbpedia timeout
* 7 # duplicate gazetteer entry with different coordinates

In [58]:
page5 = {
    "Colorado": 1,
    "Paint Mines Interpretive Park": 1,
    "Colorado Springs": 1,
    "Westcliffe": 1,
    "Florence": 1,
    "Turmeric Indian & Nepalese Restaurant": 3,
    "Silver Cliff": 1,
    "Smokey Jack Observatory": 1,
    "La Veta": 1,
    "Spanish Peaks": 1,
    "Wahatoya State Wildlife Area": 3,
    "Ryus Avenue Bakery": 1,
    "Great Sand Dunes National Park": 1,
    "Great Sand Dunes": 2,
    "Piñon Flats": 3,
    "Zapata Ranch": 1,
    "Zapata Falls": 1,
    "The Crestone Peaks": 1,
    "Crestone": 1,
    "Crestone Ziggurat": 3, 
    "San Luis Valley": 1,
    "Valley View Hot Springs": 1,
    "Crestone Brewing Company": 3,
    "Baca National Wildlife Refuge": 1,
    "Willow Lake": 3,
    "Black Canyon of the Gunnison National Park": 4,
    "Gunnison River": 1,
    "Paonia": 1,
    "North Fork Valley": 3,
    "Bross Hotel": 1,
    "Paonia State Park": 1,
    "Ragged Mountains": 3, 
    "Paonia Reservoir": 1,
    "Colorado National Monument": 1,
    "Bin 707": 2, # might be that unify lookup results missed it place on some exception
    "Wedding Canyons": 3,
    "Book Cliffs View": 1,
    "Saddlehorn Campground": 1
}

In [59]:
sum([1 for i in page5.values() if i == 1]) / len(page5.values())

0.6842105263157895